### ISSUE TITLE
Doesn't run in wayland

### ISSUE THREAD

**Issue by rhoot** [flathub/com.sweetscape.ZeroOneZeroEditor#2]
Running `flatpak run com.sweetscape.ZeroOneZeroEditor` in a terminal prints this to stderr and immediately exits:
```
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```
`QT_QPA_PLATFORM` is set to `wayland`. If I manually set it to `xcb` before running however it does launch under XWayland.

**Comment by Mailaender** [comment]
Probably because it ships its own version of Qt. You could try linking them to SDK ones instead.
